### ISSUE TITLE
cannot choose devices on mobile or with keyboard - javascript fix

### ISSUE THREAD

**Issue by falz** [dwcarder/lookingglass#1]
Here lies a diff to tweak javascript to add support for keyboard/touchscreen. 
[lg.pl-javascript-fix.diff.txt](https://github.com/dwcarder/lookingglass/files/1779096/lg.pl-javascript-fix.diff.txt)

**Comment by dwcarder** [comment]
fixed in ab65cb5ad3bbcc0eee00098e2a06a2d5ea4b75ea
